In [1]:
from helpers import *
import numpy as np
import pandas as pd
from implementations import *

In [2]:
data_path = '../data/dataset_to_release'
x_train, x_test, y_train, train_ids, test_ids = load_csv_data(data_path)

### Get an idea of the data 

In [3]:
print("X train", x_train.shape)
print("X test", x_test.shape)

X train (328135, 321)
X test (109379, 321)


### Data cleaning 
- replace the missing values of X with the mean of the column 
- replace missing values of y with the mean of the column

- standardize the data 
- remove the column if the entire column is missing 
- but make sure you'd do the same for **x_test**

In [4]:
# y_train[y_train == -1] = 0
def standardize(x):
    """Standardize the original data set."""
    mean_x = np.mean(x, axis=0)
    x = x - mean_x
    std_x = np.std(x, axis=0)
    x = x / std_x
    return x, mean_x, std_x

x_train, _, _ = standardize(x_train)

In [5]:
col_means = np.nanmean(x_train, axis=0)
inds = np.where(np.isnan(x_train))
x_train[inds] = np.take(col_means, inds[1])

/var/folders/z_/73zvycsn54sc3l7zw11z_93m0000gn/T/ipykernel_6113/3902706106.py:1: RuntimeWarning: Mean of empty slice
  col_means = np.nanmean(x_train, axis=0)


In [6]:
x_train, x_test = np.array(x_train, dtype=np.float128), np.array(x_test, dtype=np.float128)

### Logistic regression *without* regularization
Takes 2min 42sec to train the model, when max_iters = 100

In [7]:
initial_w = np.ones(x_train.shape[1], dtype=np.float128) 
max_iters = 2
gamma = 0.5
weights, loss = logistic_regression(y_train, x_train, initial_w, max_iters, gamma)


In [10]:
print("loss", loss)
print("weights", weights)

loss nan
weights [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan n

In [9]:
## now predict with the w found 
def predict_value_logistic(w, x_test):
    """
    Args: 
        w, parameter 
        x_test 
    return: 
        y_pred

    """
    y_pred = sigmoid(np.dot(x_test, w))
    display("weights", w)
    display("sigmoid ",  sigmoid(np.dot(x_test, w)))
    y_pred[y_pred <= 0.5] = -1
    y_pred[y_pred > 0.5] = 1
    return y_pred

y_pred = predict_value_logistic(weights, x_test)
display("y_pred", y_pred)
#create_csv_submission(test_ids, y_pred, 'logistic_regression.csv')

'weights'

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, na

'sigmoid '

array([nan, nan, nan, ..., nan, nan, nan], dtype=float128)

'y_pred'

array([nan, nan, nan, ..., nan, nan, nan], dtype=float128)

### Logistic regression with regularization